# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/secret-manager/server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fsrc/secret-manager/server.proto\"N\n\x10GetSecretRequest\x12\x15\n\rapplicationId\x18\x01 \x01(\t\x12\x10\n\x08vaultURL\x18\x02 \x01(\t\x12\x11\n\tsecretKey\x18\x03 \x01(\t\"(\n\x11GetSecretResponse\x12\x13\n\x0bsecretValue\x18\x01 \x01(\t2I\n\x11GRPCSecretManager\x12\x34\n\tGetSecret\x12\x11.GetSecretRequest\x1a\x12.GetSecretResponse\"\x00\x42\x14Z\x12src/secret-managerb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.secret_manager.server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\022src/secret-manager'
  _GETSECRETREQUEST._serialized_start=35
  _GETSECRETREQUEST._serialized_end=113
  _GETSECRETRESPONSE._serialized_start=115
  _GETSECRETRESPONSE._serialized_end=155
  _GRPCSECRETMANAGER._serialized_start=157
  _GRPCSECRETMANAGER._serialized_end=230
# @@protoc_insertion_point(module_scope)
